import express from 'express';
import cors from 'cors';
import multer from 'multer';
import { chromium } from 'playwright';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import rehypeStringify from 'rehype-stringify';
import remarkRehype from 'remark-rehype';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { visit } from 'unist-util-visit';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const upload = multer({ dest: 'uploads/' });

app.use(cors());
app.use(express.json());
app.use('/assets', express.static(path.join(__dirname, 'assets')));

const PORT = 3000;

const THEMES_CSS = {
  'minimal-swiss': 'minimal-swiss.css',
  'tech-oreilly': 'tech-oreilly.css',
  'dark-cyberpunk': 'dark-cyberpunk.css',
  'academic-paper': 'academic-paper.css',
  'corporate-blue': 'corporate-blue.css',
  'editorial-magazine': 'editorial-magazine.css',
  'nature-organic': 'nature-organic.css',
  'vibrant-startup': 'vibrant-startup.css',
  'legal-formal': 'legal-formal.css',
  'sketchy-hand': 'sketchy-hand.css',
};

// Remark plugin to extract title
function extractTitle() {
  return (tree, file) => {
    let title = '';
    // Find first h1
    visit(tree, 'heading', (node, index, parent) => {
      if (node.depth === 1 && !title) {
        // Simple text extraction from children
        title = node.children.map(c => c.value).join('');
        // Remove the node from the tree so it doesn't appear in the content body
        parent.children.splice(index, 1);
        return false; // Stop visiting
      }
    });
    file.data.title = title || 'Untitled Ebook';
  };
}

async function processMarkdown(content) {
  const file = await unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(extractTitle)
    .use(remarkRehype)
    .use(rehypeStringify)
    .process(content);

  let html = String(file);
  const title = file.data.title;

  // Mermaid post-processing
  html = html.replace(/<pre><code class="language-mermaid">([\s\S]*?)<\/code><\/pre>/g, (match, code) => {
      const decoded = code.replace(/&gt;/g, '>').replace(/&lt;/g, '<').replace(/&amp;/g, '&');
      return `<div class="mermaid">${decoded}</div>`;
  });

  return { html, title };
}

function getTemplate(htmlContent, title, themeId) {
    const cssFile = THEMES_CSS[themeId] || 'minimal-swiss.css';

    // Cover page HTML
    const coverHtml = `
      <div class="cover-page">
        <div class="cover-content">
            <h1 class="cover-title">${title}</h1>
            <div class="cover-footer">Generated by Ebook Builder</div>
        </div>
      </div>
      <div class="page-break"></div>
    `;

    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${title}</title>
        <link rel="stylesheet" href="http://localhost:${PORT}/assets/base.css">
        <link rel="stylesheet" href="http://localhost:${PORT}/assets/themes/${cssFile}">
        <script src="https://cdn.jsdelivr.net/npm/mermaid@10.9.0/dist/mermaid.min.js"></script>
        <script>
            mermaid.initialize({ startOnLoad: true, theme: 'neutral' });
        </script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
        <script>hljs.highlightAll();</script>
    </head>
    <body class="theme-${themeId}">
        ${coverHtml}
        <div class="content-container">
            ${htmlContent}
        </div>
    </body>
    </html>
    `;
}

app.post('/api/preview-html', upload.single('file'), async (req, res) => {
    try {
        if (!req.file) return res.status(400).send('No file uploaded');
        const theme = req.body.theme || 'minimal-swiss';
        const content = fs.readFileSync(req.file.path, 'utf-8');

        const { html, title } = await processMarkdown(content);
        const fullHtml = getTemplate(html, title, theme);

        res.send(fullHtml);
    } catch (error) {
        console.error(error);
        res.status(500).send('Error processing markdown');
    } finally {
        if (req.file) fs.unlinkSync(req.file.path);
    }
});

app.post('/api/generate-pdf', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) return res.status(400).send('No file uploaded');
    const theme = req.body.theme || 'minimal-swiss';
    const content = fs.readFileSync(req.file.path, 'utf-8');

    const { html, title } = await processMarkdown(content);
    const fullHtml = getTemplate(html, title, theme);

    const browser = await chromium.launch();
    const page = await browser.newPage();

    await page.setContent(fullHtml, { waitUntil: 'networkidle' });

    // Wait for mermaid
    if (fullHtml.includes('class="mermaid"')) {
        try {
           await page.waitForSelector('.mermaid svg', { timeout: 5000 });
        } catch(e) {
            console.log("Mermaid wait timeout");
        }
    }

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
      margin: { top: '20mm', bottom: '20mm', left: '20mm', right: '20mm' },
      footerTemplate: '<div style="font-size: 10px; text-align: center; width: 100%; font-family: sans-serif;"><span class="pageNumber"></span> / <span class="totalPages"></span></div>',
      headerTemplate: '<div></div>'
    });

    await browser.close();

    res.contentType('application/pdf');
    res.send(pdfBuffer);

  } catch (error) {
    console.error(error);
    res.status(500).send('Error generating PDF');
  } finally {
    if (req.file) fs.unlinkSync(req.file.path);
  }
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
